"""added a join class called Book_Genre

Revision ID: 21392d6de333
Revises: d4d9e8a4bac7
Create Date: 2022-11-12 15:44:21.671769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21392d6de333'
down_revision = 'd4d9e8a4bac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book__genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book__genre')
    # ### end Alembic commands ###
